source "http://rubygems.org"

gemspec

# For Compass AE developemnt
gem 'erp_base_erp_svcs', :path => '../erp_base_erp_svcs'
gem 'erp_tech_svcs', :path => '../erp_tech_svcs'

group :development, :test do
  gem 'erp_dev_svcs', :path => '../erp_dev_svcs'
  gem "test-unit", "~> 3.2.5"
  gem "factory_girl_rails", "~> 4.8"
  gem "rspec-rails", "~> 3.6"
  gem "simplecov", "~> 0.15"
  gem "sqlite3", "~> 1.3"
end
