source "http://rubygems.org"

gemspec

# For Compass AE developemnt
gem 'erp_base_erp_svcs', :path => '../erp_base_erp_svcs'
gem 'erp_tech_svcs', :path => '../erp_tech_svcs'

group :development, :test do
  gem 'erp_dev_svcs', :path => '../erp_dev_svcs'
  gem "test-unit", "~> 3.2.5"
  gem "cucumber-rails", "~> 1.3.0"
  gem "database_cleaner", "~> 1.6.1"
  gem "factory_girl_rails", "~> 4.1.0"
  gem "rspec-rails", "~> 2.12.0"
  gem "simplecov", "~> 0.7.1"
  gem "spork", "~> 0.9.2"
  gem "sqlite3", "~> 1.3.6"
end
