# TODO putting keys in this file is not safe.  Need to find a way to test without saving these keys

common: &common
  access_key_id: AKIAJOKABKXRFMG73LCA
  secret_access_key: 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
  bucket: compass-ae-test
    
production:
  <<: *common

development:
  <<: *common

test:
  <<: *common

spec:
  <<: *common
