source "http://rubygems.org"

# For Compass AE developemnt
gem 'erp_base_erp_svcs', path: '../erp_base_erp_svcs'
gem 'erp_tech_svcs', path: '../erp_tech_svcs'
gem 'erp_app', path: '../erp_app'
gem 'erp_orders', path: '../erp_orders'
gem 'erp_products', path: '../erp_products'
gem 'erp_txns_and_accts', path: '../erp_txns_and_accts'
gem 'erp_agreements', path: '../erp_agreements'
gem 'erp_commerce', path: '../erp_commerce'

gemspec

group :development, :test do
  gem 'erp_dev_svcs', :path => '../erp_dev_svcs'
  gem "test-unit", "~> 3.2.5"
  gem "factory_girl_rails", "~> 4.8"
  gem "rspec-rails", "~> 3.6"
  gem "simplecov", "~> 0.15"
  gem "sqlite3", "~> 1.3"
end
