source "http://rubygems.org"

gemspec

group :development, :test do
  gem "test-unit", "~> 3.2.5"
  gem "factory_girl_rails", "~> 4.8"
  gem "rspec-rails", "~> 3.6"
  gem "simplecov", "~> 0.15"
  gem "sqlite3", "~> 1.3"
end
